// Generated by gencpp from file beginner_turtorials/Num.msg
// DO NOT EDIT!


#ifndef BEGINNER_TURTORIALS_MESSAGE_NUM_H
#define BEGINNER_TURTORIALS_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_turtorials
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num1(0)
    , num2(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int64_t _num1_type;
  _num1_type num1;

   typedef int64_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::beginner_turtorials::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_turtorials::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::beginner_turtorials::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::beginner_turtorials::Num > NumPtr;
typedef boost::shared_ptr< ::beginner_turtorials::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_turtorials::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_turtorials::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_turtorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'beginner_turtorials': ['/home/yayayo/catkin_ws/src/beginner_turtorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_turtorials::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_turtorials::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_turtorials::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_turtorials::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_turtorials::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_turtorials::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_turtorials::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b7233452eef3749ca025e90606b0956";
  }

  static const char* value(const ::beginner_turtorials::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b7233452eef3749ULL;
  static const uint64_t static_value2 = 0xca025e90606b0956ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_turtorials::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_turtorials/Num";
  }

  static const char* value(const ::beginner_turtorials::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_turtorials::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num1\n\
int64 num2\n\
";
  }

  static const char* value(const ::beginner_turtorials::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_turtorials::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_turtorials::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_turtorials::Num_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TURTORIALS_MESSAGE_NUM_H
